# Generated by Django 4.2.19 on 2025-02-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=300)),
                ('phone', models.IntegerField()),
                ('password', models.CharField()),
                ('preferred_contact', models.BooleanField()),
                ('additional_info', models.TextField()),
            ],
        ),
    ]
