# Generated by Django 4.2.19 on 2025-02-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additional_info',
            field=models.TextField(default='Medication Plan:'),
        ),
    ]
