# Generated by Django 4.2.19 on 2025-02-13 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0005_appointment_additional_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
