# Generated by Django 4.2.19 on 2025-02-14 17:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0006_rename_created_at_appointment_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='features',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='doctor',
            name='firstname',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_address',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='doctor',
            name='lastname',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialisation',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='firstname',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='lastname',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_contact',
            field=models.BooleanField(default=None),
        ),
    ]
