# Generated by Django 4.2.19 on 2025-02-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0009_alter_doctor_email_alter_doctor_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='username',
            new_name='user',
        ),
    ]
