# Generated by Django 4.2.19 on 2025-02-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0010_rename_username_doctor_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='title',
            new_name='degree',
        ),
    ]
