# Generated by Django 4.2.19 on 2025-02-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0011_rename_title_doctor_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='features',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialisation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='preferred_contact',
        ),
    ]
