# Generated by Django 4.2.19 on 2025-02-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0014_doctor_address_doctor_city_doctor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lastname',
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='doctor',
            name='practice_name',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
