# Generated by Django 4.2.19 on 2025-02-14 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0015_remove_doctor_firstname_remove_doctor_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.BooleanField(default='Patient')),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='specialisation',
            new_name='specialisations',
        ),
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_appointments.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_appointments.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor_appointments.location'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_specialisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor_appointments.specialisation'),
        ),
    ]
