# Generated by Django 4.2.19 on 2025-02-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0016_features_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='additional_info',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(default=None),
        ),
    ]
