# Generated by Django 4.2.19 on 2025-02-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0017_alter_appointment_additional_info_alter_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.CharField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='role',
            field=models.CharField(blank=True, default=None),
        ),
    ]
