# Generated by Django 4.2.19 on 2025-02-14 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0018_doctor_role_patient_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='role',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='role',
        ),
    ]
