# Generated by Django 4.2.19 on 2025-02-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0019_remove_doctor_role_remove_patient_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='preferred_contact',
            field=models.CharField(default=None),
        ),
    ]
