# Generated by Django 4.2.19 on 2025-02-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0020_alter_patient_preferred_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='features',
            field=models.CharField(blank=True),
        ),
    ]
