# Generated by Django 4.2.19 on 2025-02-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0022_delete_role_alter_doctor_phone_number_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor', 'appointment_date'), name='unique_appointment'),
        ),
    ]
