# Generated by Django 4.2.19 on 2025-02-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0023_appointment_unique_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='city',
        ),
    ]
