# Generated by Django 4.2.19 on 2025-02-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0026_remove_location_location_location_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialisation',
            old_name='specialisation',
            new_name='specialisation_name',
        ),
    ]
