# Generated by Django 4.2.19 on 2025-02-15 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0027_rename_specialisation_specialisation_specialisation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[\\d\\-\\(\\)\\s]+$', 'Phone number must only contain numbers, spaces, dashes, or parentheses.')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[\\d\\-\\(\\)\\s]+$', 'Phone number must only contain numbers, spaces, dashes, or parentheses.')]),
        ),
    ]
