# Generated by Django 4.2.19 on 2025-04-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0028_alter_doctor_phone_number_alter_patient_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='specialisation',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='locations',
            field=models.ManyToManyField(related_name='doctors', to='doctor_appointments.location'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='features',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialisations',
        ),
        migrations.AlterField(
            model_name='patient',
            name='preferred_contact',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialisations',
            field=models.ManyToManyField(related_name='doctors', to='doctor_appointments.specialisation'),
        ),
    ]
